# Generated by Django 2.0.1 on 2018-01-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180128_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
