# Generated by Django 2.0.1 on 2018-01-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180131_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_name',
        ),
    ]
