# Generated by Django 2.0.1 on 2018-02-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180131_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
    ]
